#! /bin/bash

#set -x

# the name of the directory where the exer files will be stored.
# Right now it's using the directory of the main exec script
EXER_DB="$(dirname "$0")/exercises_db"

# The plain file DB lol
EXER_LIST="${EXER_DB}/exercises.list"

#Temp files where I'm keeping the randomized exercises are stored
CLEAN_LIST=/tmp/clean.tmp
RAND_LIST=/tmp/random_exer_list.tmp

EXER_NAME=''
MIN_REPS=0
MAX_REPS=0
SUCCESS=0

# get the name of this executable (script)
EXEC_NAME=${0##*/}
EXEC_NAME=${EXEC_NAME/\//}

e_flag=''
a_flag=''
d_flag=''
num_to_display=1

print_usage() 
{
   echo 
   printf "Usage: $EXEC_NAME [-eah] [-d] [-n number] ]\n"
   echo
   echo "Gives you a random number of reps and an exercise to maintain that"
   echo "glorius boody"
   echo
   echo "    -e Edit the exercise file"
   echo "    -a Add an exercise using a helper script"
   echo "    -d Delete an exercise"
   echo "    -n *number* Get multiple exercises"
   echo "    -h Print this page"
}

while getopts 'eadhn:' flag
do
  case "${flag}" 
  in
    e) e_flag='true' ;; # Edit an exercise
    a) a_flag='true' ;; # Add an exercise to the list
    d) d_flag='true' ;; # Get a description along with the exercise
    n) num_to_display="${OPTARG}" ;; # Get multiple exercises
    h) print_usage 
       exit $SUCCESS ;;
    *) print_usage
       exit 1 ;;
  esac
done

if [ "$e_flag" = 'true' ]
then
   vim "$EXER_LIST"
   exit $SUCCESS 
fi

if [ "$a_flag" = 'true' ]
then
   add_exer
   exit $SUCCESS 
fi

to_lower() {
  echo "$1" | tr '[:upper:]' '[:lower:]'
}

get_description()
{
   local description_file_name="$1"
   if [ -e "${description_file_name}" ]
   then
      exit 1
   fi

   # create the exercise description file
   echo > "${EXER_DB}/${description_file_name}"
   
   echo "Type the exercise description (press ctrl-d to submit?)."
   while read -r user_line
   do
      echo "$user_line" >> "${EXER_DB}/${description_file_name}"
      fmt "${EXER_DB}/${description_file_name}" > /tmp/exer.tmp
      mv /tmp/exer.tmp "${EXER_DB}/${description_file_name}" 
   done
}

set_exer_name() 
{
  while true
  do
     echo -n "Exercise name: "
     read -r name_input

     local exer_name=`to_lower "$name_input"`

     if [ -n "$exer_name" ]
     then
        EXER_NAME="$exer_name"
        break
     fi
  done
}

set_exer_min_reps() 
{
  while true
  do
     echo -n "Min reps: "
     read -r rep_input

     if [[ "$rep_input" =~ ^[1-9][0-9]*$ ]]
     then
        MIN_REPS="$rep_input"
        break
     fi
  done
}

set_exer_max_reps() 
{
  while true
  do
     echo -n "Max reps: "
     read -r rep_input

     if [[ "$rep_input" =~ ^[1-9][0-9]*$ ]]
     then
        if [ $rep_input -gt $MIN_REPS ]
        then
           MAX_REPS="$rep_input"
           break
        fi
     fi
  done
}

add_exer()
{
   set_exer_name
   set_exer_min_reps
   set_exer_max_reps

   description_file_name=`echo "${EXER_NAME}"     \
                         | sed 's/[[:space:]]/_/g' \
                         | sed 's/$/\.exer/'`
   echo "Rep units? (second, minute, hour, rep): "
   read type
   get_description "${description_file_name}"

   echo "${EXER_NAME},"             \
        "${MIN_REPS},"              \
        "${MAX_REPS},"              \
        "${description_file_name}," \
        "${type},"                  \
        >> ${EXER_LIST}  

   sort "${EXER_LIST}" > "${EXER_LIST}.tmp"
   mv  "${EXER_LIST}.tmp" "${EXER_LIST}"
}

# exit if num_to_display (number of exercises) is not an integer
(( $num_to_display + 0 )) ||  exit 1

# Preprocess the list of exercises
(sed '/^[ 	]*$/d' $EXER_LIST | sed '/^[ 	]*#/d') >${CLEAN_LIST}

# Get the number of exercises in the list
NUM_WORK_OUTS=`wc -l <${CLEAN_LIST}`

# Create a list with the exercises in random order
(cat ${CLEAN_LIST} | sort -R | head -n ${num_to_display}) >${RAND_LIST}

# Iterate through the list of exercises that is in random order
while read -r line
do
   EXER_NAME=$(echo "$line" | cut -d , -f 1)
   REP_MIN=$(echo "$line" | cut -d , -f 2)
   REP_MAX=$(echo "$line" | cut -d , -f 3)
   DESCRIPTION_FILE=`echo $line      \
                     | cut -d , -f 4 \
                     | sed 's/^[[:space:]][[:space:]]*//'`
   TYPE=`echo "$line"                                      \
                     | cut -d , -f 5                       \
                     | sed 's/[[:space:]][[:space:]]*$//'  \
                     | sed 's/^[[:space:]][[:space:]]*//'`  
   
   # the +1 makes it so that the reps include REP_MAX.
   let "RANDOM_REPS = $RANDOM % ($REP_MAX - $REP_MIN + 1) + $REP_MIN"
   
   if [ $RANDOM_REPS = '1' ]
   then
      # Display the name of the exercise, singular time units
      case "$TYPE" in
      second|minute|hour|day|year|decade|light-year)
         echo "Do a ${EXER_NAME} for 1 ${TYPE}." ;;
      *)
         echo "Do 1 ${EXER_NAME}." ;;
      esac
   else
      # Display the name of the exercise, plural time units
      case "$TYPE" in
      second|minute|hour|day|year|decade|light-year)
         echo "Do a ${EXER_NAME} for ${RANDOM_REPS} ${TYPE}s." ;;
      *)
         echo "Do ${RANDOM_REPS} ${EXER_NAME}s." ;;
      esac
   fi

   if [ "${d_flag}" = 'true' ]
   then
      # show the description if user used the description flag
      echo --------------- Description:
      cat "${EXER_DB}/${DESCRIPTION_FILE}" 
      echo ---------------------------
   fi
done < ${RAND_LIST}

